Repository ansible-collections/arista.eos, pull requests merged in 2022-04, with the labels that each got.

#337 Copy ingore txt
  changelogs/fragments/0-ignore.yml
  tests/sanity/ignore-2.14.txt
Labels: gate, mergeit

#340 eos_snmp_server: Fix to change communities without an ACL attached
  changelogs/fragments/fix_snmp_server_communities.yaml
  plugins/module_utils/network/eos/rm_templates/snmp_server.py
  tests/unit/modules/network/eos/test_eos_snmp_server.py
Labels: mergeit

#343 eos_facts: change default subset to min
  changelogs/fragments/eos_facts_update.yaml
  docs/arista.eos.eos_facts_module.rst
  plugins/module_utils/network/eos/argspec/facts/facts.py
  plugins/modules/eos_facts.py
  tests/integration/targets/eos_facts/tests/cli/default_facts.yaml
  tests/integration/targets/eos_facts/tests/eapi/default_facts.yaml
Labels: mergeit

#330 Fix for issue #329: Formatting in protocol_options causes errors...
  changelogs/fragments/fix_eos_acls_protocol_options.yml
  plugins/module_utils/network/eos/config/acls/acls.py
Labels: mergeit

#342 Add bgp_global neighbor bfd parser and fix send-community parser
  changelogs/fragments/add_bgp_global_neighor_bfd.yaml
  docs/arista.eos.eos_bgp_global_module.rst
  plugins/module_utils/network/eos/argspec/bgp_global/bgp_global.py
  plugins/module_utils/network/eos/config/bgp_global/bgp_global.py
  plugins/module_utils/network/eos/rm_templates/bgp_global.py
  plugins/modules/eos_bgp_global.py
  tests/unit/modules/network/eos/test_eos_bgp_global.py
Labels: mergeit

#341 Fix parser for bgp maximum-paths
  changelogs/fragments/fix_bgp_global_ecmp_render.yaml
  plugins/module_utils/network/eos/rm_templates/bgp_global.py
  test-requirements.txt
  tests/unit/modules/network/eos/test_eos_bgp_global.py
Labels: mergeit

#312 updated references of base plugins to netcommon
  changelogs/fragments/netcommon_ref_update.yaml
  galaxy.yml
  plugins/cliconf/eos.py
  plugins/httpapi/eos.py
  plugins/terminal/eos.py
Labels: blocks_release, mergeit

#346 Apply changes from https://github.com/ansible/ansible/pull/56407 to h…
  .pre-commit-config.yaml
  changelogs/fragments/346-httpapi.yaml
  docs/arista.eos.eos_bgp_module.rst
  docs/arista.eos.eos_httpapi.rst
  docs/arista.eos.eos_interface_module.rst
  docs/arista.eos.eos_l2_interface_module.rst
  docs/arista.eos.eos_l3_interface_module.rst
  docs/arista.eos.eos_linkagg_module.rst
  docs/arista.eos.eos_logging_module.rst
  docs/arista.eos.eos_static_route_module.rst
  docs/arista.eos.eos_vlan_module.rst
  plugins/httpapi/eos.py
Labels: mergeit

#347 Eos release 5.0.0
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/0-ignore.yml
  changelogs/fragments/346-httpapi.yaml
  changelogs/fragments/add_bgp_global_neighor_bfd.yaml
  changelogs/fragments/eos_facts_remove_warning.yaml
  changelogs/fragments/eos_facts_update.yaml
  changelogs/fragments/fix_bgp_global_ecmp_render.yaml
  changelogs/fragments/fix_eos_acls_protocol_options.yml
  changelogs/fragments/fix_snmp_server_communities.yaml
  changelogs/fragments/netcommon_ref_update.yaml
Labels: mergeit
